### PR TITLE
Add Sandy Wars

### PR DESCRIPTION
**Pull request by CoWinkKeyDinkInc**
I created a Sand Wars knockoff that can be added to the repository. Other than a few minor cosmetic changes the map should play pretty much the same, including being able to build anywhere inside the lava area. A small change (that I might've brought back) I added is now the players can damage themselves from their own TNT they ignited.

The only thing I'm missing is the map.png since Optifine isn't working for me to take a screenshot nicely, but that doesn't really matter. Also I've noticed that wool never burns in the map, is there a way to enable burning in the XML?

I was also considering removing the golden apples and the tnt from the `<itemremove>` tag, if people liked that better. I haven't played that in a while so I am not sure if these changes were good.

### CODE REVIEW

**Comment by CrazyisCreeps** [comment]
Do you have any gamerules that you set in the world, such as disabling fire tick?

**Comment by CoWinkKeyDinkInc** [comment]
I enabled the rule in the XML so hopefully it works, it's all good now

**Comment by CrazyisCreeps** [comment]
Hopefully it works, or do you have a way to test and ensure it works?

**Comment by CoWinkKeyDinkInc** [comment]
yeah I can test it in a few minutes

**Comment by CrazyisCreeps** [comment]
That would be awesome! 

On another note, maybe we can explore another map name option? Sand Wars 2 makes it sound like it's a sequel to the original / part of a series rather than a clone. What do you think? If you don't share the same line of thought in the slightest let me know, I don't want to come off as bossy here 🙂

**Comment by CoWinkKeyDinkInc** [comment]
yeah, I mean if it is a big deal we could change the name or make the map "gravel wars" lmao. I would have it be sand vs gravel but gravel has a stronger blast resistance, so it wouldn't be a fair map.

**Comment by CrazyisCreeps** [comment]
What about something like "Sandy Wars"? Has the same vibe, but isn't the same and doesn't require you to alter the map itself.

**Comment by CoWinkKeyDinkInc** [comment]
Can't think of anything better, so let's go with that, I managed to edit the signs in MCEdit :+1: 

I also added 8 glass as a killreward

**Comment by dustinn1** [comment]
The folder should be named sandy_wars. Other than that, looks good. Since the map is a clone of sand wars, using its map.png shouldn’t be problem: https://raw.githubusercontent.com/MCResourcePile/overcast-bow-images/master/maps/sand_wars.png

**Comment by CoWinkKeyDinkInc** [comment]
I haven't noticed the consistency in folder names, I have now corrected that

**Comment by CrazyisCreeps** [comment]
Alright looks good.

For reference, here's the second part of adding a map to the site: https://github.com/MCResourcePile/mcresourcepile.github.io/commit/ea1a1f25b2879a3afa070b40fa223968ce4265ab

**Pull request merged**
